import assert from "node:assert/strict";
import { lstat, mkdir, mkdtemp, open, readFile, readdir, rename, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { basename, join } from "node:path";
import { describe, test } from "node:test";

import { writeExclusiveArtifactSet } from "../../scripts/lib/exclusive-artifact-set-writer.mts";

const ROOT = join(import.meta.dirname, "..", "..");
const ACTIVE_GENERATORS = [
  "scripts/generate-m5b-fedex-system-acquired-prewrite.mts",
  "scripts/generate-m5b-fedex-gate-b-synthetic-prewrite.mts",
] as const;

describe("M5b frozen generator destinations", () => {
  test("an occupied destination preserves its bytes and prevents every missing sibling write", async () => {
    const root = await mkdtemp(join(tmpdir(), "atliera-m5b-exclusive-writer-"));
    try {
      for (let occupiedIndex = 0; occupiedIndex < 3; occupiedIndex += 1) {
        const caseRoot = join(root, `occupied-${occupiedIndex}`);
        await mkdir(caseRoot);
        const paths = [join(caseRoot, "first.json"), join(caseRoot, "middle.json"), join(caseRoot, "last.html")];
        await writeFile(paths[occupiedIndex]!, "frozen sentinel bytes\n", { flag: "wx" });

        await assert.rejects(
          () => writeExclusiveArtifactSet([
            { path: paths[0]!, data: "new first\n" },
            { path: paths[1]!, data: "new middle\n" },
            { path: paths[2]!, data: "new last\n" },
          ]),
          /destination already exists/i,
        );

        assert.equal(await readFile(paths[occupiedIndex]!, "utf8"), "frozen sentinel bytes\n");
        assert.deepEqual(await readdir(caseRoot), [basename(paths[occupiedIndex]!)]);
      }
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });

  test("both active generators use the exclusive set writer and never direct-write", async () => {
    for (const relativePath of ACTIVE_GENERATORS) {
      const source = await readFile(join(ROOT, relativePath), "utf8");
      assert.match(source, /writeExclusiveArtifactSet/);
      assert.doesNotMatch(source, /\bwriteFile\b/);
    }
    const writerSource = await readFile(join(ROOT, "scripts/lib/exclusive-artifact-set-writer.mts"), "utf8");
    assert.match(writerSource, /open\(path, "wx"\)/);
  });

  test("an ordinary post-reservation failure preserves every created final-path remnant", async () => {
    const root = await mkdtemp(join(tmpdir(), "atliera-m5b-failed-remnants-"));
    try {
      const paths = [join(root, "first.json"), join(root, "middle.json"), join(root, "last.html")];
      const invalidData = 1 as unknown as string | Uint8Array;

      await assert.rejects(
        () => writeExclusiveArtifactSet([
          { path: paths[0]!, data: "written before failure\n" },
          { path: paths[1]!, data: invalidData },
          { path: paths[2]!, data: "not reached\n" },
        ]),
        { code: "ERR_INVALID_ARG_TYPE" },
      );

      for (const path of paths) assert.equal((await lstat(path)).isFile(), true);
      assert.equal(await readFile(paths[0]!, "utf8"), "written before failure\n");
      assert.equal(await readFile(paths[1]!, "utf8"), "");
      assert.equal(await readFile(paths[2]!, "utf8"), "");
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });

  test("a substitution before failure handling preserves the replacement and displaced remnant", async () => {
    const root = await mkdtemp(join(tmpdir(), "atliera-m5b-substitution-"));
    const probePath = join(root, "prototype-probe");
    const probe = await open(probePath, "wx");
    const handlePrototype = Object.getPrototypeOf(probe) as { writeFile: typeof probe.writeFile };
    const originalWriteFile = handlePrototype.writeFile;
    await probe.close();

    const paths = [join(root, "first.json"), join(root, "middle.json"), join(root, "last.html")];
    const displacedPath = join(root, "displaced-first.json");
    const primaryFailure = new Error("injected post-reservation failure");
    let injected = false;
    handlePrototype.writeFile = (async () => {
      if (!injected) {
        injected = true;
        await rename(paths[0]!, displacedPath);
        await writeFile(paths[0]!, "concurrent replacement bytes\n", { flag: "wx" });
        throw primaryFailure;
      }
    }) as typeof probe.writeFile;

    try {
      await assert.rejects(
        () => writeExclusiveArtifactSet(paths.map((path) => ({ path, data: "generated bytes\n" }))),
        (error) => error === primaryFailure,
      );

      assert.equal(await readFile(paths[0]!, "utf8"), "concurrent replacement bytes\n");
      assert.equal(await readFile(displacedPath, "utf8"), "");
      assert.equal(await readFile(paths[1]!, "utf8"), "");
      assert.equal(await readFile(paths[2]!, "utf8"), "");
    } finally {
      handlePrototype.writeFile = originalWriteFile;
      await rm(root, { recursive: true, force: true });
    }
  });

  test("no pathname deletion covers substitution after identity observation without a timing race", async () => {
    // Node cannot atomically bind dev+ino to pathname deletion. Prohibiting deletion
    // proves every substitution interleaving, including after any identity check.
    const writerSource = await readFile(join(ROOT, "scripts/lib/exclusive-artifact-set-writer.mts"), "utf8");
    assert.doesNotMatch(
      writerSource,
      /import\s*\{[^}]*\b(?:unlink|rm|rmdir|rename)(?:Sync)?\b[^}]*\}\s*from\s*["']node:fs(?:\/promises)?["']/s,
    );
    assert.doesNotMatch(writerSource, /\b(?:unlink|rm|rmdir|rename)(?:Sync)?\s*\(/);
  });
});
