import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import test from "node:test";

const DOC = join(
  import.meta.dirname,
  "..",
  "..",
  "docs",
  "runbooks",
  "runtime-model-only-product-preview-runtime-smoke-approval-packet.md",
);

const privateLeakagePatterns = [
  /api[_-]?key/i,
  /bearer /i,
  /authorization header/i,
  /private-provider-evidence/i,
  /raw_provider_output/i,
  /raw_harness_transport_request/i,
  /screened account text committed: true/i,
];

test("runtime smoke approval is exactly one future provider request and docs-only", () => {
  const doc = readFileSync(DOC, "utf8");
  for (const required of [
    /Status: pre-run docs-only approval packet/i,
    /This PR does not execute a provider call/i,
    /Input decision: `runtime-model-only-product-preview-post-comparison-decision\.md`/i,
    /Input hardening: `runtime-model-only-product-preview-runtime-hardening\.md`/i,
    /approval_id: runtime-model-only-product-preview-runtime-smoke-20260604d/i,
    /approval_kind: one_call_single_slot_runtime_model_mode_smoke/i,
    /max_attempts: 1/i,
    /max_provider_calls: 1/i,
    /approved_max_cost_usd: 1/i,
    /route_ref: gpt-5\.5-openai-codex-20260602a/i,
    /provider_ref: openai-codex/i,
    /model_label: gpt-5\.5/i,
    /transport_kind: model-only-codex-auth/i,
    /corpus_ref: product-preview\/runtime-smoke-single-slot-v1/i,
    /prompt_contract_ref: prompts\/product-preview-model-only-v1/i,
    /slot_role: calibration/i,
    /runtime_mode: model-only-smoke/i,
    /dry_run: true/i,
    /provider_calls_executed: 0/i,
    /provider_spend_authorized_by_plan: false/i,
    /raw_private_evidence_read: false/i,
    /network_access_performed: false/i,
    /If planner validation fails, stop before provider access/i,
    /invoke transport at most once/i,
    /stop after one provider request even if the output contract fails/i,
    /max_attempts_greater_than_1: false/i,
    /max_provider_calls_greater_than_1: false/i,
    /paid_fallback_allowed: false/i,
    /retry_allowed_without_new_approval: false/i,
    /additional_slots_allowed: false/i,
    /live_expansion_allowed: false/i,
    /provider_comparison_execution_allowed: false/i,
    /default_model_selection_allowed: false/i,
    /graph_ingestion_allowed: false/i,
    /workshop_runtime_render_allowed: false/i,
    /background_orchestrator_allowed: false/i,
    /production_writes_allowed: false/i,
    /tools_allowed: false/i,
    /web_search_allowed: false/i,
    /plugins_allowed: false/i,
    /mcp_allowed: false/i,
    /shell_allowed: false/i,
    /file_access_allowed: false/i,
    /retrieval_allowed: false/i,
    /session_carryover_allowed: false/i,
    /status_renderer_used/i,
    /retry_requires_new_approval: true/i,
    /authorizes_provider_call: true/i,
    /authorizes_provider_call_count: 1/i,
    /authorizes_retry: false/i,
    /authorizes_live_expansion: false/i,
    /authorizes_provider_comparison_execution: false/i,
    /authorizes_default_model_selection: false/i,
    /authorizes_graph_ingestion: false/i,
    /authorizes_background_orchestrator_bypass: false/i,
    /authorizes_production_use: false/i,
    /product_readiness_claim: false/i,
    /production_readiness_claim: false/i,
    /launch_readiness_claim: false/i,
  ]) assert.match(doc, required);

  for (const forbidden of [
    /max_attempts: [2-9]/i,
    /max_provider_calls: [2-9]/i,
    /approved_max_cost_usd: (?:[2-9]|[1-9][0-9])/i,
    /authorizes_provider_call_count: [2-9]/i,
    /authorizes_retry: true/i,
    /authorizes_live_expansion: true/i,
    /authorizes_provider_comparison_execution: true/i,
    /authorizes_default_model_selection: true/i,
    /authorizes_graph_ingestion: true/i,
    /authorizes_background_orchestrator_bypass: true/i,
    /authorizes_production_use: true/i,
    /product_readiness_claim: true/i,
    /production_readiness_claim: true/i,
    /launch_readiness_claim: true/i,
    /default production model/i,
    ...privateLeakagePatterns,
  ]) assert.doesNotMatch(doc, forbidden);
});
