import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import test from "node:test";

const DOC = join(
  import.meta.dirname,
  "..",
  "..",
  "docs",
  "runbooks",
  "runtime-model-only-live-proof-execution-status.md",
);

test("runtime model-only live proof execution status records one sanitized output-contract completion and remains non-authorizing", () => {
  const doc = readFileSync(DOC, "utf8");

  for (const required of [
    /Status: completed for one approved output-contract-compatible synthetic provider request/i,
    /Approval packet: `runtime-model-only-live-proof-output-contract-approval-packet\.md`/i,
    /output-contract-compatible attempt was performed after PR #183 merged/i,
    /sanitized public status only/i,
    /PR #176 approved exactly one synthetic attempt/i,
    /PR #177 recorded that attempt as a sanitized exception/i,
    /PR #178 approved exactly one corrected retry/i,
    /PR #179 recorded that corrected retry as a sanitized exception/i,
    /PR #180 approved exactly one parameter-compatible attempt/i,
    /PR #181 recorded that parameter-compatible attempt as a sanitized exception/i,
    /PR #182 merged the no-call output-contract collector and guardrail/i,
    /PR #183 approved exactly one output-contract-compatible attempt/i,
    /streamed `response\.output_text\.delta` text was the canonical output source/i,
    /completed item text was not concatenated with delta text/i,
    /strict exact JSON proof parsing was enforced/i,
    /status: completed/i,
    /reason_code: synthetic_model_only_live_proof_completed/i,
    /stable_error_code: none/i,
    /provider_calls_executed: 1/i,
    /provider_spend: false/i,
    /observed_cost_usd: 0/i,
    /approved_max_cost_usd: 1/i,
    /accepted_output_received: true/i,
    /output_source: delta/i,
    /input_tokens_observed: 125/i,
    /output_tokens_observed: 16/i,
    /raw_request_committed: false/i,
    /raw_response_committed: false/i,
    /model_output_committed: false/i,
    /private_evidence_committed: false/i,
    /credential_value_observed: false/i,
    /raw_evidence_committed: false/i,
    /route_ref: gpt-5\.5-openai-codex-20260602a/i,
    /provider_ref: openai-codex/i,
    /model_label: gpt-5\.5/i,
    /transport_kind: model-only-codex-auth/i,
    /no tools/i,
    /no shell/i,
    /no file access/i,
    /no web search/i,
    /no plugins/i,
    /no MCP/i,
    /no retrieval/i,
    /no session carryover/i,
    /no provider comparison/i,
    /no default model selection/i,
    /no provider lock-in/i,
    /no production writes/i,
    /no production deployment/i,
    /no autonomous-agent substitution/i,
    /exact tiny synthetic model-only route/i,
    /the delta-first output collector produced one accepted proof object/i,
    /the accepted proof object satisfied the exact top-level output contract/i,
    /not an approval packet and does not authorize another provider request/i,
    /max_attempts: 1/i,
    /one_call_only: true/i,
    /output_contract_compatible_attempt_only: true/i,
    /output_contract_approval_consumed: true/i,
    /authorizes_provider_call: false/i,
    /authorizes_candidate_calls: false/i,
    /authorizes_comparison_run: false/i,
    /default_model_selection_claim: false/i,
    /provider_lock_in: false/i,
    /production_readiness_claim: false/i,
    /product_readiness_claim: false/i,
    /launch_readiness_claim: false/i,
    /retry_requires_new_approval: true/i,
    /no automatic retry/i,
    /no production readiness claim/i,
    /requires another fresh approval packet/i,
  ]) {
    assert.match(doc, required, `execution status runbook must contain: ${required}`);
  }

  for (const forbidden of [
    /provider_spend: true/i,
    /provider_calls_executed: [2-9]/i,
    /authorizes_provider_call: true/i,
    /authorizes_candidate_calls: true/i,
    /authorizes_comparison_run: true/i,
    /default model selected: true/i,
    /default production model/i,
    /provider_lock_in: true/i,
    /\bproduction[ -]ready\b/i,
    /product ready/i,
    /launch ready/i,
    /retries authorized/i,
    /comparison authorized/i,
    /raw prompt/i,
    /raw request body/i,
    /raw response body/i,
    /private evidence path/i,
    /raw_evidence_committed: true/i,
    /credential_value_observed: true/i,
  ]) {
    assert.doesNotMatch(doc, forbidden, `execution status runbook must not contain: ${forbidden}`);
  }
});
